const fs=require('fs'),vm=require('vm'),assert=require('assert');
const sourcePath=require('path').resolve(__dirname,'../assets/workbench/app.js');
let doc;
class Element {
  constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.parentNode=null;this.attrs={};this.style={};this.listeners={};this.hidden=false;this.disabled=false;this._text='';this.className='';this.value='';this.scrollTop=0;this.pauseCalls=0;this.loadCalls=0;this.classList={add:(...v)=>{this.className=[...new Set(this.className.split(' ').concat(v))].join(' ');},remove:(v)=>{this.className=this.className.split(' ').filter(x=>x!==v).join(' ');},toggle:(v,b)=>{const has=this.className.split(' ').includes(v);const on=b===undefined?!has:b;if(on)this.classList.add(v);else this.classList.remove(v);return on;}};}
  get isConnected(){return !!this._connected||!!this.parentNode?.isConnected;}
  get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}
  set textContent(v){this._text=String(v);this.children.forEach(c=>c.parentNode=null);this.children=[];}
  get childElementCount(){return this.children.length;}
  get lastElementChild(){return this.children.at(-1);}
  append(...items){for(let child of items){if(child.tagName==='#FRAGMENT'){this.append(...child.children.slice());continue;}if(typeof child==='string'){const e=new Element('#text');e.textContent=child;child=e;}child.remove();child.parentNode=this;this.children.push(child);}}
  replaceChildren(...items){this.children.forEach(c=>c.parentNode=null);this.children=[];this._text='';this.append(...items);}
  remove(){if(this.parentNode){this.parentNode.children=this.parentNode.children.filter(c=>c!==this);this.parentNode=null;}}
  setAttribute(k,v){this.attrs[k]=String(v);if(k==='src')this.src=String(v);}
  getAttribute(k){return this.attrs[k]??null;}
  removeAttribute(k){delete this.attrs[k];if(k==='src')delete this.src;}
  addEventListener(k,f){(this.listeners[k]??=[]).push(f);}
  click(){this.listeners.click?.forEach(f=>f({target:this,preventDefault(){}}));}
  focus(){doc.activeElement=this;}
  getClientRects(){return this.hidden?[]:[{}];}
  pause(){this.pauseCalls++;}
  load(){this.loadCalls++;}
  matches(s){if(s.startsWith('.'))return this.className.split(' ').includes(s.slice(1));if(s==='details[open]')return this.tagName==='DETAILS'&&this.open;return this.tagName.toLowerCase()===s;}
  querySelectorAll(selector){const selectors=selector.split(','),result=[];function visit(e){for(const child of e.children){if(selectors.some(s=>child.matches(s)))result.push(child);visit(child);}}visit(this);return result;}
  querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
}
const ids=new Map();doc={activeElement:null,body:new Element('body'),getElementById(id){if(!ids.has(id)){const e=new Element(id==='lightbox-image'?'img':'div');e.id=id;e._connected=true;if(['detail-drawer','media-lightbox'].includes(id))e.hidden=true;ids.set(id,e);}return ids.get(id);},createElement:t=>new Element(t),createElementNS:(_,t)=>new Element(t),createDocumentFragment:()=>new Element('#fragment'),createTextNode:t=>{const e=new Element('#text');e.textContent=t;return e;},querySelectorAll:()=>[],addEventListener(){}};doc.body._connected=true;
const requests=[],session=new Map(),ctx={document:doc,window:{addEventListener(){}},location:{search:'?token=test-access&run=test',origin:'http://127.0.0.1:8765',pathname:'/',hash:'',href:'http://127.0.0.1:8765/?token=test-access&run=test'},history:{replaceState(){}},sessionStorage:{getItem:k=>session.get(k),setItem:(k,v)=>session.set(k,v)},navigator:{onLine:true},URL,URLSearchParams,AbortController,setTimeout:()=>1,clearTimeout(){},setInterval(){},matchMedia:()=>({matches:true}),EventSource:class{},fetch:(url,options)=>new Promise(resolve=>requests.push({url,options,resolve})),console};
let source=fs.readFileSync(sourcePath,'utf8').replace(/\r\n/g,'\n');source=source.replace('  loadRuns(true);\n})();','  globalThis.ui={app,openDetail,closeDetail,renderDetail,refreshSelected,previewURL,fieldValue,mediaStatus,mediaCandidates,detail:()=>detailView};\n})();');assert(source.includes('globalThis.ui='));vm.createContext(ctx);vm.runInContext(source,ctx);
const ui=ctx.ui;ui.app.runId='test';ui.app.transport='live';let passed=0;function test(name,f){f();passed++;console.log('PASS '+name);}
const image={available:true,asset_id:'opaque-image',mime:'image/png',size:1024,origin:'local_cache'},video={available:true,asset_id:'opaque-video',mime:'video/mp4',size:4096,origin:'local_cache'},base={id:'nds:with / 中文.nds',system:'nds',file:'with / 中文.nds',name:'测试游戏',status:'done',updated_at:'2026-10-03T10:00:00Z',unknown:['players'],sources:[],missing:[],media:{covers:{present:true,path:'/device/covers/test.png',extras:{preview:image}},videos:{present:true,path:'/device/videos/test.mp4',extras:{preview:video}},manuals:{present:true,path:'/device/manual.pdf'}}},detail={...base,details:{metadata:{name:'测试中文标题',desc:'实际简介'.repeat(200),developer:'开发公司',publisher:'发行公司',genre:'动作',players:'2',releasedate:'20200101T000000',rating:'0.8',path:'./with / 中文.nds'},history:{playcount:'0',playtime:'3661',lastplayed:'20261003T100000'},protected:{favorite:'true',hidden:'false'},file:{actual_path:'/storage/ROMS/with / 中文.nds',size:12345},extra:{fields:[{tag:'private',text:'保留的扫描私有信息'}]}}};
test('opaque endpoint and token; no arbitrary source URL',()=>{const url=new URL(ui.previewURL({...image,url:'https://evil.invalid/secret'}));assert.equal(url.origin,ctx.location.origin);assert.equal(url.pathname,'/api/runs/test/media/opaque-image');assert.equal(url.searchParams.get('token'),'test-access');assert.equal(ui.previewURL({available:false,asset_id:'x'}),null);});
test('readable zero values, booleans, duration, ratings and dates',()=>{assert.equal(ui.fieldValue('playcount','0'),'0');assert.equal(ui.fieldValue('favorite','true'),'是');assert.equal(ui.fieldValue('hidden','false'),'否');assert(ui.fieldValue('playtime','3661').includes('1 小时 1 分 1 秒'));assert(ui.fieldValue('rating','0.8').includes('8.0 / 10'));assert.equal(ui.fieldValue('releasedate','20200101T000000'),'2020-01-01');});
test('recorded and missing states are separate from preview availability',()=>{assert.equal(ui.mediaStatus(null,null).state,'unrecorded');assert.equal(ui.mediaStatus({present:true},null).state,'scanned');assert.equal(ui.mediaStatus({present:false},image).state,'missing');assert.equal(ui.mediaStatus({present:true,verification:'historical_receipt'},null).state,'recorded');});
test('candidate images retained',()=>{assert.equal(ui.mediaCandidates({path:'a',extras:{preview:image,candidates:[{available:true,asset_id:'other-image',mime:'image/png'}]}}).length,2);});
(async()=>{
 ui.openDetail(base,new Element('button'));assert.equal(requests.length,1);assert(new URL(requests[0].url).pathname.endsWith('/jobs/nds%3Awith%20%2F%20%E4%B8%AD%E6%96%87.nds'));requests[0].resolve({status:200,ok:true,json:async()=>({job:detail})});await new Promise(setImmediate);await new Promise(setImmediate);
 test('exact detail shows nested metadata, full description, history and optional media',()=>{const content=doc.getElementById('detail-content').textContent;assert(content.includes('测试中文标题'));assert(content.includes(detail.details.metadata.desc));assert(content.includes('游玩次数'));assert(content.includes('1 小时 1 分 1 秒'));assert(content.includes('保留的扫描私有信息'));assert(content.includes('玩家人数尚未核实'));assert(content.includes('游戏手册'));assert(content.includes('/storage/ROMS/with / 中文.nds'));});
 const currentVideo=doc.getElementById('detail-content').querySelector('video');assert(currentVideo);currentVideo.currentTime=12;const toggle=doc.getElementById('detail-content').querySelector('.description-toggle');toggle.click();doc.getElementById('detail-drawer').scrollTop=713;
 test('real previews only; present manual gets no fabricated image',()=>{assert.equal(ui.detail().cards.get('manuals').preview.querySelectorAll('img').length,0);assert(ui.detail().cards.get('manuals').message.textContent.includes('没有可预览文件'));assert.equal(currentVideo.src,new URL(ui.previewURL(video)).href);assert(currentVideo.controls);});
 test('live refresh preserves player, playback time, description and scroll',()=>{ui.app.selected={...detail,updated_at:'2026-10-03T10:01:00Z'};ui.renderDetail();assert.equal(doc.getElementById('detail-content').querySelector('video'),currentVideo);assert.equal(currentVideo.currentTime,12);assert.equal(toggle.getAttribute('aria-expanded'),'true');assert.equal(doc.getElementById('detail-drawer').scrollTop,713);ui.app.transport='offline';ui.renderDetail();assert.equal(doc.getElementById('detail-content').querySelector('video'),currentVideo);});
 test('closing drawer releases video source and stops playback',()=>{ui.closeDetail();assert(currentVideo.pauseCalls>0);assert.equal(currentVideo.src,undefined);assert(doc.getElementById('detail-drawer').hidden);});
 ui.app.transport='live';ui.openDetail({...base,id:'A',name:'A'},new Element('button'));const first=requests.at(-1);ui.openDetail({...base,id:'B',name:'B'},new Element('button'));const second=requests.at(-1);first.resolve({status:200,ok:true,json:async()=>({job:{...detail,id:'A'}})});second.resolve({status:200,ok:true,json:async()=>({job:{...detail,id:'B'}})});await new Promise(setImmediate);await new Promise(setImmediate);
 test('out of order responses never show a previously selected game',()=>{assert.equal(ui.app.selected.id,'B');assert.equal(ui.detail().id,'B');});
 console.log(passed+' UI logic tests passed (isolated DOM; no browser or network).');
})().catch(e=>{console.error(e);process.exit(1);});
